---
- name: Update APT package cache
  apt: update_cache=yes

- name: Install python-apt  (Required by ANSIBLE)
  command: apt-get -y install python-apt

- name : Update all packages to the latest version
  apt: upgrade=dist

- name: Install packages
  apt: name={{ item }} state=installed update_cache=yes cache_valid_time=3600
  with_items:
    - autoconf
    - bison
    - build-essential
    - curl
    - git
    - htop
    - imagemagick
    - libcurl3
    - libcurl3-gnutls
    - libcurl4-openssl-dev
    - libncurses5-dev
    - libqt5webkit5-dev
    - libreadline6-dev
    - libsqlite3-dev
    - libssl-dev
    - libyaml-dev
    - mailutils
    - nodejs
    - nodejs-legacy
    - npm
    - postfix
    - python-dev
    - python-pip
    - qt5-default
    - redis-server
    - zlib1g-dev

- name: Create application group
  group: name={{ group_name }}

- name: Create application user
  user: name={{ user_name }} group={{ group_name }} shell=/bin/bash home={{ user_home_path }}

- name: Create profile.d directory
  file: path={{ profile_d_path }} state=directory owner={{ user_name }} group={{ group_name }}

- name: Create ~/.bash_profile which loads all from ~/profile.d
  template: src=bash_profile.j2 dest={{ user_home_path }}/.bash_profile owner={{ user_name }} group={{ group_name }}

- name: Remove Apache2
  apt: name={{ item }} state=absent purge=yes force=yes
  with_items:
    - apache2
    - apache2-utils
  sudo: yes
