---
- hosts: all
  gather_facts: False
  become: true

  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)


# Basics
- hosts:  all
  become: true
  roles:
    - bearandgiraffe.base
    - bearandgiraffe.ruby
    - {
      role:           bearandgiraffe.vim,
      vim_username:   '{{ username }}',
      vim_group_name: '{{ group_name }}'
    }
    - bearandgiraffe.node
    - bearandgiraffe.yarn
    - bearandgiraffe.phantomjs

# DB
- hosts:  all
  become: true
  roles:
    - mysql

# Servers
- hosts:  all
  become: true
  roles:
    - {
      role:               bearandgiraffe.nginx,
      nginx_home_path:    '{{ path }}',
      nginx_db_user:      '{{ db_user }}',
      nginx_db_password:  '{{ db_password }}',
      nginx_server_type:  '{{ server_type }}'
    }

- hosts:  all
  become: '{{ username }}'
  roles:
    - puma

# Remove Apache
- hosts:  all
  user:   vagrant
  tasks:
    - name: Ramove Apache2
      apt: name={{ item }} state=absent purge=yes force=yes
      with_items:
       - apache2
       - apache2-utils
      become: true

# Rails
- hosts:  all
  roles:
    - rails

# Redis
- hosts:  all
  become: true
  roles:
    - bearandgiraffe.redis

# Heroku
- hosts:  all
  become: true
  roles:
    - bearandgiraffe.heroku-cli

- hosts: all
  become: true
  roles:
    - bearandgiraffe.selenium
